#!/bin/sh
# The ARP Scanner (arp-scan) is Copyright (C) 2005-2016 Roy Hills
#
# This file is part of arp-scan.
#
# arp-scan is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# arp-scan is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with arp-scan.  If not, see <http://www.gnu.org/licenses/>.
#
# check-run1 -- Shell script to test arp-scan basic functionality
#
# Author: Roy Hills
# Date: 9 March 2006
#
# This shell script checks that "arp-scan --help" and "arp-scan --version"
# work.  These options don't use much of the arp-scan functionality, so if
# they fail, then there is a fundamental problem with the program.
#
TMPFILE=/tmp/arp-scan-test.$$.tmp
#
echo "Checking arp-scan --help ..."
$srcdir/arp-scan --help > $TMPFILE
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
grep '^Report bugs or send suggestions at ' $TMPFILE >/dev/null
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
echo "ok"
#
echo "Checking arp-scan --version ..."
$srcdir/arp-scan --version > $TMPFILE
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
grep '^Copyright (C) ' $TMPFILE >/dev/null
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
echo "ok"
#
rm -f $TMPFILE
