#!/usr/bin/env perl
#
# Copyright 2006-2022 Roy Hills
#
# This file is part of arp-scan.
#
# arp-scan is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# arp-scan is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with arp-scan.  If not, see <http://www.gnu.org/licenses/>.
#
# get-iab -- Obsolete script
#
# Author: Roy Hills
# Date: 16 March 2006
#
use warnings;
use strict;
#
my $message =
qq/$0 is no longer needed and was depreciated in arp-scan 1.99
get-oui is now used to fetch all of the Ethernet MAC-Vendor
mappings from the various IEEE registries.  See get-oui(1) for
details.
/;
#
die $message;
