.\" Copyright (C) Roy Hills, NTA Monitor Ltd.
.\"
.\" Copying and distribution of this file, with or without modification,
.\" are permitted in any medium without royalty provided the copyright
.\" notice and this notice are preserved.
.\"
.\" $Id: get-iab.1 7780 2006-06-20 08:32:01Z rsh $
.TH GET-IAB 1 "March 30, 2007"
.\" Please adjust this date whenever revising the man page.
.SH NAME
get-iab \- Fetch the arp-scan IAB file from the IEEE website
.SH SYNOPSIS
.B get-iab
.RI [ options ]
.SH DESCRIPTION
.B get-iab
fetches the Ethernet IAB file from the IEEE website, and saves it in the
format used by arp-scan.
.PP
The IAB file contains all of the IABs (Individual Address Blocks)
that have been registered with IEEE.  Each IAB entry in the file specifies
the first 36-bits of the 48-bit Ethernet hardware address, leaving the
remaining 12-bits for use by the registering organisation.  For example
the IAB entry "0050C2003", registered to Microsoft, applies to any
Ethernet hardware address from
.I 00:50:c2:00:30:00
to
.I 00:50:c2:00:3f:ff
inclusive.  Each IAB assignment represents a total of 2^12 (4,096)
Ethernet addresses.
.PP
Major Ethernet hardware vendors typically use an OUI registration rather
than an IAB registration.  See
.BR get-oui (1)
for details.
.PP
This script can be used to update the
.B arp-scan
IAB file from the latest data on the IEEE website.  It is relatively rare
to see Ethernet addresses from IAB registrations, so the IAB file is not
as important as the OUI file.
.PP
The IAB data is fetched from the URL
.I http://standards.ieee.org/regauth/oui/iab.txt
and the output file is saved to the file
.I ieee-iab.txt
in the current directory. The URL to fetch the data from can be changed with
the
.B -u
option, and the output file name can be changed with the
.B -f
option.
.PP
The
.I ieee-iab.txt
file that is produced by this script is used by
.B arp-scan
to determine the Ethernet card vendor from its hardware address.
.PP
The directory that
.B arp-scan
will look for the
.I ieee-iab.txt
file depends on the options used when it was built.  If it was
built using the default options, then it will look in
.IR /usr/local/share/arp-scan .
.SH OPTIONS
.TP
.B -h
Display a brief usage message and exit.
.TP
.B -f <fn>
Write the output to the specified file instead of the default
.I ieee-iab.txt.
.TP
.B -u <URL>
Use the specified URL to fetch the raw IAB data from instead of the default
.I http://standards.ieee.org/regauth/oui/iab.txt
.TP
.B -v
Display verbose progress messages.
.SH FILES
.TP
.I ieee-iab.txt
The default output file.
.SH EXAMPLES
.nf
$ get-iab -v
Renaming ieee-iab.txt to ieee-iab.txt.bak
Fetching IAB data from http://standards.ieee.org/regauth/oui/iab.txt
Fetched 230786 bytes
Opening output file ieee-iab.txt
1535 IAB entries written to file ieee-iab.txt
.fi
.SH NOTES
.B get-iab
is implemented in Perl, so you need to have the Perl interpreter installed on
your system to use it.
.PP
.B get-iab
uses the
.I LWP::Simple
Perl module to fetch the data from the IEEE website. You must have this module
installed on your system for
it to work. This module is available on most distributions, often called
.IR libwww-perl .
It is also available in source form from CPAN.
.PP
You can use a proxy server by defining the
.I http_proxy
environment variable.
.SH AUTHOR
Roy Hills <Roy.Hills@nta-monitor.com>
.SH "SEE ALSO"
.TP
.BR arp-scan (1)
.TP
.BR get-oui (1)
.TP
.BR arp-fingerprint (1)
.PP
.I http://www.nta-monitor.com/wiki/
The arp-scan wiki page.
